# Generated by Django 3.2 on 2023-05-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20230526_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='user',
        ),
    ]
